### PR TITLE
improve: use registerBufferProtocol for file resolving

### LINKED ISSUE #7: Not correctly served static files
[Issuehunt badges](https://issuehunt.io/r/sindresorhus/electron-serve/issues/7)

Hi, i noticed that some static files fetched without correct HTTP headers and its causes compilation issues (please see the attached file)

image
image
image

<details>
<summary>
<b>IssueHunt Summary</b>
</summary>

### Sponsors (Total: $50.00)

- [issuehunt issuehunt](https://issuehunt.io/u/issuehunt) ($50.00)

### Tips

- Checkout the [Issuehunt explorer](https://issuehunt.io/r/sindresorhus/electron-serve/) to discover more funded issues.
- Need some help from other developers? [Add your repositories](https://issuehunt.io/r/new) on IssueHunt to raise funds.
</details>

### PR DESCRIPTION
**Pull request by distolma**
Fixes #7

### CODE REVIEW

**Comment by distolma** [comment]
#7

**Comment by sindresorhus** [comment]
@hadeeb Can you help review this?

**Comment by sindresorhus** [comment]
@distolma Can you include a PR description that describes your changes? For example, why it's necessary to switch to `registerBufferProtocol`.

**Comment by sindresorhus** [comment]
Looks like this PR is moot with #14 landing.

**Comment by hadeeb** [comment]
IMO, adding mimeTypes is reasonable and is required if we want to serve es6 modules.
 I'll see if I can add it with file protocol.

**Comment by sindresorhus** [comment]
@hadeeb Did you have a chance to look into it?

**Comment by hadeeb** [comment]
Electron >=5 supports sending headers along with the filepath.

At work, we ended up using StreamProtocol.

**Pull request closed without merging**
